### PR TITLE
Handle null paths

### LINKED ISSUE #47: hash_file throws an error with path being NULL
I suspect it's because there are more than two ways(the ones which we track) one can "open" a file descriptor. For example if they were to call `socket(2)` to obtain a new socket and then later called `close(2)` to close the socket, our code would crash because no path was ever associated with the file descriptor being closed.

Now checking for null is a valid option but i am afraid it might hide potential bugs in the future(paths that should be tracked actually aren't). Nevertheless this is what i recommend we should do, and we shouldn't worry about this problem since switching to the model we previously described(that of opening the files upon finding the `open(2)` calls) will make the problem disappear.

### PR DESCRIPTION
**Pull request by fvalasiad**
Now ignores `FILE_INFO`s that aren't associated with any traced opened file. Closes #47

### CODE REVIEW

File: src/tracer.c [hunk 1]
```diff
@@ -205,8 +205,10 @@ handle_syscall(pid_t pid, const struct ptrace_syscall_info *entry,
 
 	    finfo = find(pid)->finfo + fd;
 
-	    finfo->hash = hash_file(finfo->path);
-	    record_fileuse(pid, finfo->path, finfo->purpose, finfo->hash);
+	    if(finfo->path != (char *) 0) {
```
Comment (zvr) [inline src/tracer.c:208]: How did you manage to have `if(` instead of `if (` (space after keyword)?
Don't you automatically invoke indent?

Comment (fvalasiad) [reply src/tracer.c:208]: @zvr I am kind of new to using git hooks and yeah it apparently doesn't work. What I've done after reading manuals was essentially modify **pre-commit** script in **.git/hooks/** so that it looks like this:

`#!/bin/bash

indent $1
exit 0`

i also removed the `.sample` as the instructions guided me to do. What am i missing?

Comment (zvr) [reply src/tracer.c]:
```bash
$ cat .git/hooks/pre-commit
#!/usr/bin/env bash

for f in $(git diff --cached --diff-filter=ACM --name-only); do
        if [[ "$f" == *.[ch] ]]; then
                INDENT_PROFILE=/home/zvr/github/gsoc2022--build-recorder/.indent.pro indent "$f" && git add "$f"
        fi
done
```

Comment (fvalasiad) [reply src/tracer.c]: @zvr Hmmmm git claims that the first argument is each file being commited, but i guess this approach could be used as well.

I guess what was wrong was that i wasn't `git add`ing it afterwards, and i should perhaps also add the file check.

**Review by zvr — APPROVED** [review]
